### ISSUE TITLE
Installation error due to 404 when trying to instsall pyseg from dev level

### ISSUE THREAD

**Issue by DcShepherd** [scipion-em/scipion-em-pyseg#55]
--2022-01-20 13:23:49--  https://github.com/anmartinezs/pyseg_system/archive/refs/heads/jj_fix_preseg_oriented.zip
Resolving github.com (github.com)... 52.64.108.95
Connecting to github.com (github.com)|52.64.108.95|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://codeload.github.com/anmartinezs/pyseg_system/zip/refs/heads/jj_fix_preseg_oriented [following]
--2022-01-20 13:23:49--  https://codeload.github.com/anmartinezs/pyseg_system/zip/refs/heads/jj_fix_preseg_oriented
Resolving codeload.github.com (codeload.github.com)... 3.105.64.153
Connecting to codeload.github.com (codeload.github.com)|3.105.64.153|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2022-01-20 13:23:49 ERROR 404: Not Found.

Pyseg can be installed if I pull form the Master branch but not the Developer branch due to the above error.

**Comment by JorMaister** [comment]
This should work now. Sorry for the inconvenience.
