### ISSUE TITLE
Improving gcc g++ requirements

### ISSUE THREAD

**Issue by MohamadHarastani** [scipion-em/scipion-em-pyseg#59]
Hello,
Why don't you use gcc-7 and g++-7 binaries instead of asking the user to re-link gcc/g++ to gcc-7/g++-7?
I have Ubuntu 20, and I installed gcc-7 and g++-7. If I look in my path I find:
```
$ ls /usr/bin/gcc* /usr/bin/g++*
/usr/bin/g++    /usr/bin/g++-8  /usr/bin/gcc    /usr/bin/gcc-8  /usr/bin/gcc-ar    /usr/bin/gcc-ar-8  /usr/bin/gcc-nm    /usr/bin/gcc-nm-8  /usr/bin/gcc-ranlib    /usr/bin/gcc-ranlib-8
/usr/bin/g++-7  /usr/bin/g++-9  /usr/bin/gcc-7  /usr/bin/gcc-9  /usr/bin/gcc-ar-7  /usr/bin/gcc-ar-9  /usr/bin/gcc-nm-7  /usr/bin/gcc-nm-9  /usr/bin/gcc-ranlib-7  /usr/bin/gcc-ranlib-9
```
Still the installation of scipion-em-pyseg fails because gcc/++ are still linked to gcc/++8. Maybe you can just use the links gcc/++-7 (or, 5 or 6).
Cheers
Mohamad

**Comment by azazellochg** [comment]
Ubuntu is great, but on HPC you normally load a module (e.g. compilers/gcc/7.3.0) that modifies your env vars.  I'm sure there's a better way to get gcc version, e.g. https://github.com/I2PC/xmipp/blob/devel/scripts/utils.py#L50
