### ISSUE TITLE
scipion-em-tomoviz  depends on pymeshfix==0.14.1

### ISSUE THREAD

**Issue by werhoog** [scipion-em/scipion-em-pyseg#82]
Hi,
I tried to install pyseg by scipion (./scipion3 installp -p scipion-em-pyseg). 
And it will automatically install related modules, including scipion-em-tomoviz.
However, scipion-em-tomoviz  depends on pymeshfix==0.14.1.

I checked, and there is no pymeshfix version 0.14.1 available. Do you have a suggestion on how to
fix this dependency?

The errors:

/opt/miniconda3/envs/scipion3/bin/python -m pip install scipion-em-pyseg==3.1.3
Collecting scipion-em-pyseg==3.1.3
 Using cached scipion_em_pyseg-3.1.3-py3-none-any.whl.metadata (4.4 kB)
Collecting scipion-em-tomo (from scipion-em-pyseg==3.1.3)
 Using cached scipion_em_tomo-3.7.1-py3-none-any.whl.metadata (5.4 kB)
Collecting scipion-em-tomoviz (from scipion-em-pyseg==3.1.3)
 Using cached scipion_em_tomoviz-3.1.4-py3-none-any.whl.metadata (1.8 kB)
Collecting scipion-em-reliontomo (from scipion-em-pyseg==3.1.3)
 Using cached scipion_em_reliontomo-3.4.0-py3-none-any.whl.metadata (4.5 kB)
Requirement already satisfied: emtable in /opt/miniconda3/envs/scipion3/lib/python3.8/site-packages (from scipion-em-reliontomo->scipion-em-pyseg==3.1.3) (0.0.14)
Collecting scipion-em-relion (from scipion-em-reliontomo->scipion-em-pyseg==3.1.3)
 Using cached scipion_em_relion-4.0.20-py3-none-any.whl.metadata (5.7 kB)
Collecting scipion-em-imod (from scipion-em-reliontomo->scipion-em-pyseg==3.1.3)
 Using cached scipion_em_imod-3.5.1-py3-none-any.whl.metadata (8.3 kB)
Requirement already satisfied: mrcfile<=1.4.3,>=1.4.0 in /opt/miniconda3/envs/scipion3/lib/python3.8/site-packages (from scipion-em-tomo->scipion-em-pyseg==3.1.3) (1.4.3)
Requirement already satisfied: scipion-em in /opt/miniconda3/envs/scipion3/lib/python3.8/site-packages (from scipion-em-tomo->scipion-em-pyseg==3.1.3) (3.7.1)
Requirement already satisfied: scipion-pyworkflow in /opt/miniconda3/envs/scipion3/lib/python3.8/site-packages (from scipion-em-tomoviz->scipion-em-pyseg==3.1.3) (3.6.0)
Collecting pyvista==0.38.5 (from scipion-em-tomoviz->scipion-em-pyseg==3.1.3)
 Using cached pyvista-0.38.5-py3-none-any.whl.metadata (13 kB)
Collecting pyvistaqt==0.10.0 (from scipion-em-tomoviz->scipion-em-pyseg==3.1.3)
 Using cached pyvistaqt-0.10.0-py3-none-any.whl.metadata (4.6 kB)
INFO: pip is looking at multiple versions of scipion-em-tomoviz to determine which version is compatible with other requirements. This could take a while.
Collecting scipion-em-tomoviz (from scipion-em-pyseg==3.1.3)
 Using cached scipion_em_tomoviz-3.1.3-py3-none-any.whl.metadata (1.8 kB)
 Using cached scipion_em_tomoviz-3.1.2-py3-none-any.whl.metadata (1.8 kB)
Collecting pyvista==0.27.4 (from scipion-em-tomoviz->scipion-em-pyseg==3.1.3)
 Using cached pyvista-0.27.4-py3-none-any.whl.metadata (11 kB)
Collecting pyvistaqt==0.3.0 (from scipion-em-tomoviz->scipion-em-pyseg==3.1.3)
 Using cached pyvistaqt-0.3.0-py3-none-any.whl.metadata (4.3 kB)
Collecting scipion-em-tomoviz (from scipion-em-pyseg==3.1.3)
 Using cached scipion_em_tomoviz-3.1.1-py3-none-any.whl.metadata (1.8 kB)
 Using cached scipion_em_tomoviz-3.1.0-py3-none-any.whl.metadata (1.8 kB)
ERROR: Cannot install scipion-em-pyseg because these package versions have conflicting dependencies.
The conflict is caused by:
   scipion-em-tomoviz 3.1.4 depends on pymeshfix==0.14.1
   scipion-em-tomoviz 3.1.3 depends on pymeshfix==0.14.1
   scipion-em-tomoviz 3.1.2 depends on pymeshfix==0.14.1
   scipion-em-tomoviz 3.1.1 depends on pymeshfix==0.14.1
   scipion-em-tomoviz 3.1.0 depends on pymeshfix==0.14.1

**Comment by azazellochg** [comment]
> I checked, and there is no pymeshfix version 0.14.1 available
it is available: https://pypi.org/project/pymeshfix/0.14.1/

Today I could not reproduce your problem. Could you post `scipion3 pip list` output?
